// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.urvanov.twino.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ru.urvanov.twino.domain.Loan;

privileged aspect Loan_Roo_Configurable {
    
    declare @type: Loan: @Configurable;
    
}
